'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
function createAssetHandler({plan,root,fixtureRoot,responses,errors,pending,requestFile,rangeFor}){
 const allowed=new Set([...Object.keys(plan.sourceHashes),...plan.fixtures.map(f=>f.path),...Object.keys(plan.aliases||{}),...(plan.optionalAbsent||[]),...(plan.optionalNegativeProbes||[]).map(p=>p.url)]);
 return(req,res)=>{let file,stat,range;
  try{file=requestFile(req.url,root,fixtureRoot);if(!allowed.has(file.rel)){errors.push('Unpinned request refused: '+file.rel);res.writeHead(403).end();return;}const negative=(plan.optionalNegativeProbes||[]).find(p=>p.url===file.rel);if(negative&&fs.existsSync(negative.root+'/'+negative.path))throw Error('negative probe changed '+file.rel);if(negative||(plan.optionalAbsent||[]).includes(file.rel)){responses.push({path:file.rel,status:404,expectedAbsent:true,optionalShellAsset:!negative,optionalNativeProbe:!!negative,settled:true});res.writeHead(404).end();return;}if(plan.aliases?.[file.rel])file=requestFile('/'+plan.aliases[file.rel],root,fixtureRoot),file.rel=decodeURIComponent(new URL(req.url,'http://local').pathname).slice(1);stat=fs.statSync(file.p);if(!stat.isFile())throw Error('not file');range=rangeFor(req.headers.range,stat.size);}catch(e){errors.push('Asset request failed: '+String(e));res.writeHead(404).end();return;}
  if(!['GET','HEAD'].includes(req.method)){res.writeHead(405).end();return;}
  const row={path:file.rel,method:req.method,start:range.start,end:range.end,size:stat.size,status:range.status,expectedBodyBytes:req.method==='HEAD'?0:Math.max(0,range.end-range.start+1),readBytes:0,fileReadEnded:false,streamClosed:false,responseFinished:false,responseClosed:false,clientConsumed:'not-observable',readSha256:null,partialReadSha256:null,settled:false};responses.push(row);
  let stream,resolve;const hash=crypto.createHash('sha256'),entry={row,promise:new Promise(r=>resolve=r),destroy:()=>stream?.destroy()};pending.add(entry);
  const settle=()=>{if(row.streamClosed&&row.responseClosed&&!row.settled){row.settled=true;pending.delete(entry);resolve();}};
  res.on('finish',()=>{row.responseFinished=true;});res.on('error',e=>errors.push('Response '+file.rel+': '+String(e)));res.on('close',()=>{row.responseClosed=true;if(stream&&!row.streamClosed)stream.destroy();settle();});
  const headers={'Content-Type':({'.js':'text/javascript','.html':'text/html','.json':'application/json','.wasm':'application/wasm','.css':'text/css'})[path.extname(file.p)]||'application/octet-stream','Content-Length':Math.max(0,range.end-range.start+1),'Cache-Control':'no-store','Cross-Origin-Opener-Policy':'same-origin','Cross-Origin-Embedder-Policy':'require-corp','Accept-Ranges':'bytes'};if(range.status===206)headers['Content-Range']=`bytes ${range.start}-${range.end}/${stat.size}`;res.writeHead(range.status,headers);
  if(req.method==='HEAD'||stat.size===0){row.fileReadEnded=stat.size===0&&req.method!=='HEAD';row.streamClosed=true;row.readSha256=row.fileReadEnded?hash.digest('hex'):null;res.end();return;}
  stream=fs.createReadStream(file.p,{start:range.start,end:range.end});stream.on('data',b=>{hash.update(b);row.readBytes+=b.length;});stream.on('end',()=>{row.fileReadEnded=true;});stream.on('error',e=>{errors.push('Stream '+file.rel+': '+String(e));res.destroy();});stream.on('close',()=>{row.streamClosed=true;const digest=hash.digest('hex');if(row.fileReadEnded&&row.readBytes===row.expectedBodyBytes){row.readSha256=digest;if(range.status===200&&plan.sourceHashes[file.rel]&&digest!==plan.sourceHashes[file.rel])errors.push('served source mismatch '+file.rel);}else row.partialReadSha256=digest;settle();});stream.pipe(res);
 };
}
async function drainStreams(pending,timeoutMs=500){let timer;try{await Promise.race([Promise.all([...pending].map(e=>e.promise)),new Promise(r=>{timer=setTimeout(r,timeoutMs);})]);}finally{clearTimeout(timer);}return{pending:pending.size,unsettled:[...pending].map(e=>({path:e.row.path,readBytes:e.row.readBytes,streamClosed:e.row.streamClosed,responseClosed:e.row.responseClosed}))};}
module.exports={createAssetHandler,drainStreams};
