'use strict';
const assert=require('node:assert/strict');
const {isNativeSetup}=require('./backend');
const native={title:'AlienShooter',visible:true,gpuLayer:null};
assert.equal(isNativeSetup({windows:[native]}),true);
assert.equal(isNativeSetup({windows:[{...native,title:'Alien Shooter'}]}),true);
assert.equal(isNativeSetup({windows:[{...native,gpuLayer:{kind:'gpu'}}]}),false);
assert.equal(isNativeSetup({windows:[{...native,visible:false}]}),false);
assert.equal(isNativeSetup({windows:[{...native,title:'Notepad'}]}),false);
console.log('Observed native setup title accepted; game GPU window cannot bypass WebGL gate PASS');
