'use strict';
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path');
const { instrument } = require('./instrument');
const root = path.resolve(__dirname, '../../wt-drakan-host-write-20261007');
const source = fs.readFileSync(path.join(root, 'tools/toyvm/emit.js'), 'utf8');
const changed = instrument(source);
assert.notEqual(changed, source);
assert.throws(() => instrument(source + source), /anchor/);
assert.throws(() => instrument(source.replace("h('mov_cr_r'", "h('missing_cr_r'")), /anchor/);
const originalHandler = source.slice(source.indexOf("  h('mov_cr_r'"), source.indexOf('// LGDT/LIDT'));
const changedHandler = changed.slice(changed.indexOf("  h('mov_cr_r'"), changed.indexOf('// LGDT/LIDT'));
assert(changedHandler.endsWith(originalHandler.slice(originalHandler.indexOf('  (if (i32.eqz'))), 'exact original handler body retained after recording');
assert.equal((changed.match(/global \$diag_cr3_last \(mut/g) || []).length, 1);
assert.equal((changed.match(/export "diag_get_cr3_last"/g) || []).length, 1);
console.log('PASS exact original-source anchors, unchanged architectural MOV-CR body and duplicate/missing rejection; no WAT compile');
