'use strict';
const fs=require('node:fs'),crypto=require('node:crypto'),path=require('node:path');
const root=__dirname;
let body='(()=>{\n';
for(const name of ['observer.js','inspect.js','sample.js'])body+=fs.readFileSync(path.join(root,name),'utf8').replace(/^const \{.*\}=require\('\.\/.*'\);\n/gm,'').replace(/^module\.exports=.*;\n/gm,'')+'\n';
body+='window.WADredmorPresentation={sample};})();\n';
fs.writeFileSync(root+'/browser-overlay.js',body);
const files=['observer.js','inspect.js','sample.js','browser-overlay.js','observer.test.js','inspect.test.js'];
const hashes=Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(root+'/'+f)).digest('hex')]));
fs.writeFileSync(root+'/live-ready.json',JSON.stringify({at:new Date().toISOString(),source:'attempt4 served45e3/40cc',runtime:false,tests:'10 lightweight JS tests PASS; actual broker/blit with fixture dirtyflush; eligibility negative fixtures',hashes},null,2)+'\n');
console.log(hashes);
