#!/usr/bin/env node
// Bundle tools/wine-agent/wine-agent.js and everything it requires (werift,
// lib/agent-pair.js, the vendored tweetnacl) into ONE file the skill ships:
//
//   skills/wine-assembly-connect/scripts/wine-agent.mjs
//   skills/wine-assembly-connect/scripts/SHA256SUMS.txt
//
// One file because an agent reading SKILL.md downloads it with a single curl
// and runs it with the node it already has: no npm, no package.json, no
// install step to go wrong. Build-time deps live in this directory's own
// package.json (npm install here once), not in the repo root.
//
//   node tools/wine-agent/build.js           build + print size and sha256
//   node tools/wine-agent/build.js --check   fail if the shipped file is stale

'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..', '..');
const OUT_DIR = path.join(ROOT, 'skills', 'wine-assembly-connect', 'scripts');
const OUT = path.join(OUT_DIR, 'wine-agent.mjs');
// .txt so the deploy's extension filter ships it; shasum -c reads any name.
const SUMS = path.join(OUT_DIR, 'SHA256SUMS.txt');

let esbuild;
try {
  esbuild = require('esbuild');
} catch (_) {
  console.error('esbuild is not installed: run  (cd tools/wine-agent && npm install)');
  process.exit(2);
}

async function bundle() {
  const result = await esbuild.build({
    entryPoints: [path.join(__dirname, 'wine-agent.js')],
    bundle: true,
    platform: 'node',
    target: 'node18',
    format: 'esm',
    minify: true,
    legalComments: 'eof',
    write: false,
    // werift depends on the same tweetnacl 1.0.3 we vendor; one copy, not two.
    alias: { tweetnacl: path.join(ROOT, 'lib', 'vendor', 'tweetnacl.js') },
    // werift is CommonJS and calls require() on node builtins; an ESM bundle
    // needs a real require for those.
    banner: {
      js: "// wine-agent: bridge an AI agent to a wine-assembly game over WebRTC.\n"
        + '// Generated by tools/wine-agent/build.js from tools/wine-agent/wine-agent.js; do not edit.\n'
        + '// Usage and API: https://wine-assembly.berrry.app/skills/wine-assembly-connect/SKILL.md\n'
        + "import { createRequire as __wa_cr } from 'module'; const require = __wa_cr(import.meta.url);",
    },
    logLevel: 'warning',
  });
  return Buffer.from(result.outputFiles[0].contents);
}

(async () => {
  const code = await bundle();
  const sha = crypto.createHash('sha256').update(code).digest('hex');
  if (process.argv.includes('--check')) {
    const shipped = fs.existsSync(OUT) ? fs.readFileSync(OUT) : null;
    if (!shipped || !shipped.equals(code)) {
      console.error(`${path.relative(ROOT, OUT)} is stale: run node tools/wine-agent/build.js`);
      process.exit(1);
    }
    console.log(`wine-agent.mjs up to date (${sha})`);
    return;
  }
  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(OUT, code);
  fs.writeFileSync(SUMS, `${sha}  wine-agent.mjs\n`);
  console.log(`${path.relative(ROOT, OUT)}  ${(code.length / 1024).toFixed(0)} KB  sha256 ${sha}`);
})().catch((err) => { console.error(err); process.exit(1); });
