'use strict';
const fs=require('fs'),path=require('path'),cp=require('child_process'),crypto=require('crypto');
const [reference,media,out]=process.argv.slice(2);
if(!reference||!media||!out)throw Error('usage: prepare.js EXACT_REFERENCE_WT ORIGINAL_REPO FRESH_OUT');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const base=media+'/scratch/runs/20261008-antara-client-origin-fix';
const accepted=JSON.parse(fs.readFileSync(base+'/browser-pins9.json'));
const commit=accepted.builtSourceCommit;
cp.execFileSync('git',['merge-base','--is-ancestor',commit,'HEAD'],{cwd:reference});
if(fs.existsSync(out))throw Error('fresh output required');
fs.mkdirSync(out,{recursive:true});fs.mkdirSync(out+'/source');
const files=[],sourceHashes={},prefix='/home/user/crimsonland-webgl-20261008';
function add(local,rel,expected){const b=fs.readFileSync(local),digest=sha(b);if(expected&&digest!==expected)throw Error('source mismatch '+rel);const dest=out+'/source/'+rel;fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,b,{flag:'wx'});files.push({path:rel,bytes:b.length,sha256:digest});sourceHashes[rel]=digest;}
for(const [rel,digest] of Object.entries(accepted.sourceHashes))add(reference+'/'+rel,rel,rel==='lib/apps.js'?accepted.originalRegistrySha256:digest);
const app=require(reference+'/lib/apps').APPS.crimsonland;
const manifest=JSON.parse(fs.readFileSync(media+'/'+app.localFileManifest));
const fixturePaths=new Set([app.exe,...app.dlls,app.localFileManifest,...manifest.files.map(f=>path.posix.join(path.posix.dirname(app.localFileManifest),typeof f==='string'?f:f.url))]);
for(const rel of fixturePaths)add(media+'/'+rel,rel);
for(const rel of Object.values(require(reference+'/lib/dll-registry').DLL_PATHS))if(typeof rel==='string'&&fs.existsSync(media+'/'+rel)&&!sourceHashes[rel])add(media+'/'+rel,rel);
const exe=files.find(f=>f.path===app.exe);if(exe.sha256!=='93cdcdc872c836e75122e3a1d41312c74761cf4736181d3541521e82f6cb2031')throw Error('original EXE mismatch');
for(const n of ['browser.js','backend.js','controls.js','assets.js','cleanup.js','lifecycle.js','preflight.js','prepare.js'])fs.copyFileSync(__dirname+'/'+n,out+'/'+n);
const pin={referenceCommit:commit,referenceBuild:true,module:sourceHashes['build/wine-assembly.wasm'],files};
fs.writeFileSync(out+'/browser-pins.json',JSON.stringify(pin,null,2));
fs.writeFileSync(out+'/serve-plan.json',JSON.stringify({paths:Object.fromEntries(files.map(f=>[f.path,'./source/'+f.path])),sourceHashes,fixtures:[],aliases:{},optionalAbsent:accepted.optionalAbsent,optionalNegativeProbes:[]},null,2));
for(const n of ['build-canonical.log','toyvm-paging.log'])fs.copyFileSync(base+'/'+n,out+'/'+n);
const provenance={referenceCommit:commit,module:pin.module,source:reference,originalMedia:media,registry:'unchanged original',referenceBuild:true,buildReceipt:'build-canonical.log',route:'ordinary Play -> PLAY GAME -> reviewed Tutorial hover -> click -> W/arrow hold across actual guest frames',limits:{transferSeconds:240,browserSeconds:300,cleanupSeconds:90},nativeRun:false,remoteRun:false};
fs.writeFileSync(out+'/provenance.json',JSON.stringify(provenance,null,2));
cp.execFileSync(process.execPath,[out+'/preflight.js',out],{stdio:'inherit'});
cp.execFileSync('tar',['-czf',out+'/runtime.tar.gz','-C',out,...fs.readdirSync(out).filter(n=>n!=='runtime.tar.gz')],{timeout:60000});
const archive=fs.readFileSync(out+'/runtime.tar.gz');
fs.writeFileSync(out+'/READY.json',JSON.stringify({...provenance,remotePrefix:prefix,pins:files.length,archiveBytes:archive.length,archiveSha256:sha(archive),status:'READY SOURCE/JS ONLY; root remote grant required after Tiberian and Antara'},null,2));
console.log(fs.readFileSync(out+'/READY.json','utf8'));
