;; Diagnostic exports only. Included in a separately compiled benchmark WASM.
(global $bl_desc (mut i32) (i32.const 0))
(func (export "bl_create") (param $width i32) (param $height i32) (result i32)
  (local $this i32) (local $e i32) (local $bits i32)
  (if (i32.eqz (global.get $bl_desc))
    (then (global.set $bl_desc (call $heap_alloc (i32.const 256)))))
  (local.set $this (call $dx_create_com_obj (i32.const 2) (i32.const 0)))
  (local.set $e (call $dx_from_this (local.get $this)))
  ;; A prefix page belongs to this allocation, so crossing into the surface
  ;; from its prefix is a valid access to the guest-owned backing allocation.
  (local.set $bits (i32.add (call $g2w (call $dib_alloc
    (i32.add (i32.mul (i32.mul (local.get $width) (local.get $height)) (i32.const 2))
      (i32.const 4096)))) (i32.const 4096)))
  (store.field DxObject width (local.get $e) (local.get $width))
  (store.field DxObject height (local.get $e) (local.get $height))
  (store.field DxObject bpp (local.get $e) (i32.const 16))
  (store.field DxObject pitch (local.get $e) (i32.mul (local.get $width) (i32.const 2)))
  (store.field DxObject misc1 (local.get $e) (local.get $bits))
  (call $dx_surf_fmt_set (local.get $e) (i32.const 1))
  (local.get $this))
(func (export "bl_bits") (param $this i32) (result i32)
  (load.field DxObject misc1 (call $dx_from_this (local.get $this))))
(func (export "bl_pending")
  (global.set $d3dim_gpu_on (i32.const 1))
  (global.set $d3dim_worker_pending (i32.const 1)))
(func (export "bl_lock") (param $this i32)
  (call $handle_IDirectDrawSurface_Lock (local.get $this) (i32.const 0)
    (global.get $bl_desc) (i32.const 0) (i32.const 0) (i32.const 0)))
(func (export "bl_unlock") (param $this i32)
  (call $handle_IDirectDrawSurface_Unlock (local.get $this) (i32.const 0)
    (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0)))
(func (export "bl_flush") (call $d3dim_worker_fence))
(func (export "bl_read") (param $wa i32) (result i32)
  (call $gl16 (call $w2g (local.get $wa))))
(func (export "bl_write") (param $wa i32) (param $value i32)
  (call $gs16 (call $w2g (local.get $wa)) (local.get $value)))
(func (export "bl_hud") (param $wa i32) (param $width i32)
  (local $x i32) (local $y i32) (local $ga i32)
  (local.set $ga (call $w2g (local.get $wa)))
  (loop $row
    (local.set $x (i32.const 0))
    (loop $pixel
      (call $gs16 (i32.add (local.get $ga)
        (i32.mul (i32.add (i32.mul (local.get $y) (local.get $width)) (local.get $x))
          (i32.const 2))) (i32.const 31))
      (local.set $x (i32.add (local.get $x) (i32.const 1)))
      (br_if $pixel (i32.lt_u (local.get $x) (i32.const 320))))
    (local.set $y (i32.add (local.get $y) (i32.const 1)))
    (br_if $row (i32.lt_u (local.get $y) (i32.const 16)))))
(func (export "bl_dc") (param $this i32) (result i32)
  (call $handle_IDirectDrawSurface_GetDC (local.get $this) (global.get $bl_desc)
    (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0))
  (call $gl32 (global.get $bl_desc)))
(func (export "bl_release_dc") (param $this i32) (param $dc i32)
  (call $handle_IDirectDrawSurface_ReleaseDC (local.get $this) (local.get $dc)
    (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0)))
(func (export "bl_getpixel") (param $dc i32) (result i32)
  (call $handle_GetPixel (local.get $dc) (i32.const 0) (i32.const 0)
    (i32.const 0) (i32.const 0) (i32.const 0))
  (i32.load (global.get $reg_base)))
(func (export "bl_gdi_hud") (param $dc i32)
  (local $i i32)
  (loop $pixels
    (drop (call $gdi_hdc_set_pixel (local.get $dc)
      (i32.rem_u (local.get $i) (i32.const 320))
      (i32.div_u (local.get $i) (i32.const 320)) (i32.const 0xff0000)))
    (local.set $i (i32.add (local.get $i) (i32.const 1)))
    (br_if $pixels (i32.lt_u (local.get $i) (i32.const 5120)))))
(func (export "bl_x87") (param $wa i32) (result i64)
  (call $fpu_exec_mem (i32.const 5) (i32.const 0) (call $w2g (local.get $wa)))
  (i64.reinterpret_f64 (call $fpu_pop)))
(func (export "bl_x87_loop") (param $wa i32) (param $n i32) (param $span i32) (result i64)
  (local $i i32) (local $value i64) (local $ga i32)
  (local.set $ga (call $w2g (local.get $wa)))
  (loop $load
    (call $fpu_exec_mem (i32.const 5) (i32.const 0)
      (i32.add (local.get $ga) (i32.rem_u (i32.mul (local.get $i) (i32.const 8)) (local.get $span))))
    (local.set $value (i64.xor (local.get $value) (i64.reinterpret_f64 (call $fpu_pop))))
    (local.set $i (i32.add (local.get $i) (i32.const 1)))
    (br_if $load (i32.lt_u (local.get $i) (local.get $n))))
  (local.get $value))
(func (export "bl_heap") (result i32) (call $g2w (call $heap_alloc (i32.const 65536))))
(func (export "bl_replace") (param $this i32) (param $wa i32)
  (local $d i32)
  (local.set $d (call $g2w (global.get $bl_desc)))
  (memory.fill (local.get $d) (i32.const 0) (i32.const 108))
  (i32.store (local.get $d) (i32.const 108))
  (i32.store offset=4 (local.get $d) (i32.const 0x800))
  (i32.store offset=36 (local.get $d) (call $w2g (local.get $wa)))
  (call $handle_IDirectDrawSurface3_SetSurfaceDesc (local.get $this) (global.get $bl_desc)
    (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0)))
(func (export "bl_release") (param $this i32) (result i32)
  (call $dx_surface_release (local.get $this)))
(func (export "bl_free") (param $wa i32)
  (call $dib_free_wasm (i32.sub (local.get $wa) (i32.const 4096))))
