'use strict';
const assert = require('node:assert/strict');
const install = require('./comi-slice-observer');
(async () => {
  let clock = 0, deadline, resolve, calls = 0;
  const promise = new Promise(r => { resolve = r; });
  const proto = { slice(n, s) { assert.equal(this, target); assert.equal(n, 77); assert.equal(s.tag, 8); calls++; return promise; } };
  const target = Object.create(proto), wine = { guestWorker: target };
  const opts = { wine, now: () => ++clock, setTimeout: fn => (deadline = fn, 1), clearTimeout() {} };
  const observer = install(opts);
  assert.equal(target.slice(77, {tag:8}), promise);
  resolve({ ms: 2, blocks: 77, yield: 0, sleepMs: 0 });
  await promise; await Promise.resolve();
  assert.equal(calls, 1); assert.equal(observer.snapshot().rows[1].data.blocks, 77);
  deadline(); assert.equal(target.slice, proto.slice); assert(!Object.hasOwn(target, 'slice'));
  const error = Error('original'); target.slice = function(){ throw error; };
  const throws = install(opts); assert.throws(() => target.slice(), e => e === error); throws.close();
  const rejection = Promise.reject(error); target.slice = () => rejection;
  const rejected = install(opts); assert.equal(target.slice(), rejection); await rejection.catch(() => {}); await Promise.resolve();
  assert.equal(rejected.snapshot().rows.at(-1).kind, 'rejected'); rejected.close();
  target.slice = () => 1; const capped = install(opts);
  for (let i=0;i<300;i++) target.slice();
  assert.equal(capped.snapshot().rows.length,512); assert(capped.snapshot().closed);
  const foreign = install(opts), replacement = () => 2; target.slice = replacement; foreign.close();
  assert.equal(target.slice,replacement); assert.equal(foreign.snapshot().errors.length,1);
  console.log('PASS same Promise/receiver/args/return/throw/rejection, descriptor cleanup, cap and foreign replacement');
})().catch(e => { console.error(e); process.exitCode=1; });
