  ;; WriteProcessMemory can replace an API entry with guest instructions.
  ;; Keep its original dispatch descriptor separate from those visible bytes.
  ;; Immutable records {next,index,originalLo,originalHi} are published into
  ;; 256 shared buckets. Restoring the original bytes restores API dispatch.
  (global $THUNK_PATCH_STATE i32 (region.addr $THUNK_PATCH_STATE 0))
  (global $THUNK_PATCH_STATE_SIZE i32 (i32.const 16))
  (func $thunk_patch_record (param $idx i32) (result i32)
    (local $table i32) (local $n i32)
    (local.set $table (i32.atomic.load offset=4 (global.get $THUNK_PATCH_STATE)))
    (if (i32.eqz (local.get $table)) (then (return (i32.const 0))))
    (local.set $n (i32.atomic.load (call $g2w (i32.add (local.get $table)
      (i32.shl (i32.and (local.get $idx) (i32.const 255)) (i32.const 2))))))
    (block $end (loop $scan
      (br_if $end (i32.eqz (local.get $n)))
      (if (i32.eq (call $gl32 (i32.add (local.get $n) (i32.const 4))) (local.get $idx))
        (then (return (call $g2w (local.get $n)))))
      (local.set $n (call $gl32 (local.get $n))) (br $scan)))
    (i32.const 0))
  (func $thunk_metadata_addr (param $idx i32) (result i32)
    (local $rec i32)
    (local.set $rec (call $thunk_patch_record (local.get $idx)))
    (if (local.get $rec) (then (return (i32.add (local.get $rec) (i32.const 8)))))
    (i32.add (global.get $THUNK_BASE) (i32.shl (local.get $idx) (i32.const 3))))
  (func $thunk_patch_changed (param $idx i32) (result i32)
    (local $rec i32)
    (local.set $rec (call $thunk_patch_record (local.get $idx)))
    (if (i32.eqz (local.get $rec)) (then (return (i32.const 0))))
    (i64.ne (i64.load offset=8 (local.get $rec))
      (i64.load (i32.add (global.get $THUNK_BASE) (i32.shl (local.get $idx) (i32.const 3))))))
  (func $thunk_entry_original (param $target i32) (result i32)
    (i32.eqz (call $thunk_patch_changed
      (i32.shr_u (i32.sub (local.get $target) (global.get $thunk_guest_base)) (i32.const 3)))))
  ;; Reserve all descriptors before the caller changes any bytes. On OOM,
  ;; partially reserved immutable records are harmless and no write occurs.
  (func $thunk_patch_prepare (param $dst i32) (param $size i32) (result i32)
    (local $first i32) (local $last i32) (local $idx i32) (local $table i32)
    (local $rec i32) (local $link i32) (local $w i32)
    (if (i32.eqz (local.get $size)) (then (return (i32.const 1))))
    (call $update_thunk_end)
    (local.set $last (i32.add (local.get $dst) (i32.sub (local.get $size) (i32.const 1))))
    (if (i32.or (i32.lt_u (local.get $last) (global.get $thunk_guest_base))
                (i32.ge_u (local.get $dst) (global.get $thunk_guest_end)))
      (then (return (i32.const 1))))
    (local.set $first (select (local.get $dst) (global.get $thunk_guest_base)
      (i32.gt_u (local.get $dst) (global.get $thunk_guest_base))))
    (if (i32.ge_u (local.get $last) (global.get $thunk_guest_end))
      (then (local.set $last (i32.sub (global.get $thunk_guest_end) (i32.const 1)))))
    (local.set $idx (i32.shr_u (i32.sub (local.get $first) (global.get $thunk_guest_base)) (i32.const 3)))
    (local.set $last (i32.shr_u (i32.sub (local.get $last) (global.get $thunk_guest_base)) (i32.const 3)))
    (loop $lock (br_if $lock (i32.atomic.rmw.cmpxchg (global.get $THUNK_PATCH_STATE) (i32.const 0) (i32.const 1))))
    (block $oom
      (local.set $table (i32.atomic.load offset=4 (global.get $THUNK_PATCH_STATE)))
      (if (i32.eqz (local.get $table)) (then
        (local.set $table (call $heap_alloc (i32.const 1024)))
        (br_if $oom (i32.eqz (local.get $table)))
        (call $zero_memory (call $g2w (local.get $table)) (i32.const 1024))
        (i32.atomic.store offset=4 (global.get $THUNK_PATCH_STATE) (local.get $table))))
      (loop $entries
        (if (i32.eqz (call $thunk_patch_record (local.get $idx))) (then
          (local.set $rec (call $heap_alloc (i32.const 16)))
          (br_if $oom (i32.eqz (local.get $rec)))
          (local.set $w (call $g2w (local.get $rec)))
          (local.set $link (call $g2w (i32.add (local.get $table)
            (i32.shl (i32.and (local.get $idx) (i32.const 255)) (i32.const 2)))))
          (i32.store (local.get $w) (i32.atomic.load (local.get $link)))
          (i32.store offset=4 (local.get $w) (local.get $idx))
          (i64.store offset=8 (local.get $w)
            (i64.load (i32.add (global.get $THUNK_BASE) (i32.shl (local.get $idx) (i32.const 3)))))
          (i32.atomic.store (local.get $link) (local.get $rec))))
        (local.set $idx (i32.add (local.get $idx) (i32.const 1)))
        (br_if $entries (i32.le_u (local.get $idx) (local.get $last))))
      (i32.atomic.store (global.get $THUNK_PATCH_STATE) (i32.const 0))
      (return (i32.const 1)))
    (i32.atomic.store (global.get $THUNK_PATCH_STATE) (i32.const 0))
    (global.set $last_error (i32.const 8)) (i32.const 0))
