  ;; Toolhelp heap snapshots and public HeapAlloc ownership.
  ;; Shared directory: lock, private-heap list, snapshot list, bucket pointer.
  ;; 1024 allocation hash buckets are allocated lazily from the guest heap.
  ;; Allocation records are {next,heap,ptr,size}.
  ;; Internal allocator bookkeeping is not a public HeapAlloc allocation.
  (global $TOOLHELP_HEAPS i32 (region.addr $TOOLHELP_HEAPS 0))
  (global $TOOLHELP_HEAPS_SIZE i32 (i32.const 16))
  (func $toolhelp_lock
    (loop $wait
      (br_if $wait (i32.atomic.rmw.cmpxchg (global.get $TOOLHELP_HEAPS) (i32.const 0) (i32.const 1)))))
  (func $toolhelp_unlock (i32.atomic.store (global.get $TOOLHELP_HEAPS) (i32.const 0)))
  (func $toolhelp_bucket (param $ptr i32) (result i32)
    (i32.add (call $g2w (i32.load offset=12 (global.get $TOOLHELP_HEAPS)))
      (i32.shl (i32.and (i32.shr_u (local.get $ptr) (i32.const 3)) (i32.const 1023)) (i32.const 2))))
  ;; Caller holds the metadata lock. Return a wasm address of the link.
  (func $toolhelp_alloc_link (param $ptr i32) (result i32)
    (local $link i32) (local $n i32) (local $steps i32)
    (if (i32.eqz (i32.load offset=12 (global.get $TOOLHELP_HEAPS))) (then (return (i32.const 0))))
    (local.set $link (call $toolhelp_bucket (local.get $ptr)))
    (loop $scan
      (local.set $n (i32.load (local.get $link)))
      (if (i32.eqz (local.get $n)) (then (return (local.get $link))))
      (if (i32.eq (call $gl32 (i32.add (local.get $n) (i32.const 8))) (local.get $ptr))
        (then (return (local.get $link))))
      (local.set $link (call $g2w (local.get $n)))
      (local.set $steps (i32.add (local.get $steps) (i32.const 1)))
      (br_if $scan (i32.lt_u (local.get $steps) (i32.const 65536))))
    (i32.const 0))
  ;; Reserve metadata before changing an allocation, so bookkeeping OOM
  ;; cannot turn a successful realloc into loss of the caller's old block.
  (func $toolhelp_alloc_reserve (param $heap i32) (param $ptr i32) (result i32)
    (local $link i32) (local $n i32)
    (call $toolhelp_lock)
    (if (i32.eqz (i32.load offset=12 (global.get $TOOLHELP_HEAPS))) (then
      (local.set $n (call $heap_alloc (i32.const 4096)))
      (if (i32.eqz (local.get $n)) (then
        (call $toolhelp_unlock) (global.set $last_error (i32.const 8)) (return (i32.const 0))))
      (call $zero_memory (call $g2w (local.get $n)) (i32.const 4096))
      (i32.store offset=12 (global.get $TOOLHELP_HEAPS) (local.get $n))
      (local.set $n (i32.const 0))))
    (if (local.get $ptr) (then
      (local.set $link (call $toolhelp_alloc_link (local.get $ptr)))
      (if (local.get $link) (then (local.set $n (i32.load (local.get $link)))))))
    (if (local.get $n) (then
      (if (i32.ne (call $gl32 (i32.add (local.get $n) (i32.const 4))) (local.get $heap))
        (then (global.set $last_error (i32.const 87)) (local.set $n (i32.const 0)))))
      (else
        (local.set $n (call $heap_alloc (i32.const 16)))
        (if (local.get $n) (then (call $zero_memory (call $g2w (local.get $n)) (i32.const 16)))
          (else (global.set $last_error (i32.const 8))))))
    (call $toolhelp_unlock)
    (local.get $n))
  (func $toolhelp_alloc_commit (param $n i32) (param $heap i32) (param $ptr i32) (param $size i32)
    (local $w i32) (local $link i32)
    (call $toolhelp_lock)
    (local.set $w (call $g2w (local.get $n)))
    (if (local.get $ptr) (then
      (if (i32.load offset=4 (local.get $w)) (then
        (local.set $link (call $toolhelp_alloc_link (i32.load offset=8 (local.get $w))))
        (if (local.get $link) (then (i32.store (local.get $link) (i32.load (local.get $w)))))))
      (local.set $link (call $toolhelp_bucket (local.get $ptr)))
      (i32.store (local.get $w) (i32.load (local.get $link)))
      (i32.store offset=4 (local.get $w) (local.get $heap))
      (i32.store offset=8 (local.get $w) (local.get $ptr))
      (i32.store offset=12 (local.get $w) (local.get $size))
      (i32.store (local.get $link) (local.get $n)))
      (else
        (if (i32.eqz (i32.load offset=4 (local.get $w)))
          (then (call $heap_free (local.get $n))))))
    (call $toolhelp_unlock))
  (func $toolhelp_alloc_remove (param $heap i32) (param $ptr i32) (result i32)
    (local $link i32) (local $n i32) (local $ok i32)
    (local.set $ok (i32.const 1))
    (call $toolhelp_lock)
    (local.set $link (call $toolhelp_alloc_link (local.get $ptr)))
    (if (local.get $link) (then
      (local.set $n (i32.load (local.get $link)))
      (if (local.get $n) (then
        (if (i32.eq (call $gl32 (i32.add (local.get $n) (i32.const 4))) (local.get $heap))
          (then (i32.store (local.get $link) (call $gl32 (local.get $n))) (call $heap_free (local.get $n)))
          (else (local.set $ok (i32.const 0))))))))
    (call $toolhelp_unlock)
    (local.get $ok))
  (func $toolhelp_heap_add (param $heap i32)
    (call $toolhelp_lock)
    (call $gs32 (i32.add (local.get $heap) (i32.const 4)) (i32.load offset=4 (global.get $TOOLHELP_HEAPS)))
    (i32.store offset=4 (global.get $TOOLHELP_HEAPS) (local.get $heap))
    (call $toolhelp_unlock))
  (func $toolhelp_heap_remove (param $heap i32)
    (local $link i32) (local $n i32) (local $bucket i32) (local $steps i32)
    (call $toolhelp_lock)
    (local.set $link (region.addr $TOOLHELP_HEAPS 4))
    (block $removed (loop $heaps
      (local.set $n (i32.load (local.get $link)))
      (br_if $removed (i32.eqz (local.get $n)))
      (if (i32.eq (local.get $n) (local.get $heap)) (then
        (i32.store (local.get $link) (call $gl32 (i32.add (local.get $n) (i32.const 4)))) (br $removed)))
      (local.set $link (call $g2w (i32.add (local.get $n) (i32.const 4))))
      (local.set $steps (i32.add (local.get $steps) (i32.const 1)))
      (br_if $heaps (i32.lt_u (local.get $steps) (i32.const 65536)))))
    ;; Destroying a private heap releases its actual public allocations too.
    (if (i32.eqz (i32.load offset=12 (global.get $TOOLHELP_HEAPS)))
      (then (call $toolhelp_unlock) (return)))
    (loop $buckets
      (local.set $link (i32.add (call $g2w (i32.load offset=12 (global.get $TOOLHELP_HEAPS))) (i32.shl (local.get $bucket) (i32.const 2))))
      (local.set $steps (i32.const 0))
      (block $next (loop $allocations
        (local.set $n (i32.load (local.get $link)))
        (br_if $next (i32.eqz (local.get $n)))
        (if (i32.eq (call $gl32 (i32.add (local.get $n) (i32.const 4))) (local.get $heap))
          (then
            (i32.store (local.get $link) (call $gl32 (local.get $n)))
            (call $heap_free (call $gl32 (i32.add (local.get $n) (i32.const 8))))
            (call $heap_free (local.get $n)))
          (else (local.set $link (call $g2w (local.get $n)))))
        (local.set $steps (i32.add (local.get $steps) (i32.const 1)))
        (br_if $allocations (i32.lt_u (local.get $steps) (i32.const 65536)))))
      (local.set $bucket (i32.add (local.get $bucket) (i32.const 1)))
      (br_if $buckets (i32.lt_u (local.get $bucket) (i32.const 1024))))
    (call $toolhelp_unlock))
  ;; Snapshot records: next, heap count, flags, then immutable heap IDs.
  (func $toolhelp_snapshot_link (param $handle i32) (result i32)
    (local $link i32) (local $n i32) (local $steps i32)
    (local.set $link (region.addr $TOOLHELP_HEAPS 8))
    (loop $scan
      (local.set $n (i32.load (local.get $link)))
      (if (i32.eqz (local.get $n)) (then (return (i32.const 0))))
      (if (i32.eq (local.get $n) (local.get $handle)) (then (return (local.get $link))))
      (local.set $link (call $g2w (local.get $n)))
      (local.set $steps (i32.add (local.get $steps) (i32.const 1)))
      (br_if $scan (i32.lt_u (local.get $steps) (i32.const 65536))))
    (i32.const 0))
  (func $toolhelp_close (param $handle i32) (result i32)
    (local $link i32)
    (call $toolhelp_lock)
    (local.set $link (call $toolhelp_snapshot_link (local.get $handle)))
    (if (local.get $link) (then
      (i32.store (local.get $link) (call $gl32 (local.get $handle)))
      (call $heap_free (local.get $handle))))
    (call $toolhelp_unlock)
    (select (i32.const 1) (i32.const -1) (i32.ne (local.get $link) (i32.const 0))))
  (func $toolhelp_return (param $value i32) (param $args i32)
    (i32.store (global.get $reg_base) (local.get $value))
    (i32.store offset=16 (global.get $reg_base)
      (i32.add (i32.load offset=16 (global.get $reg_base)) (i32.shl (i32.add (local.get $args) (i32.const 1)) (i32.const 2)))))
  (func $handle_CreateToolhelp32Snapshot (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $count i32) (local $heap i32) (local $snap i32) (local $w i32) (local $i i32)
    (if (i32.and (i32.ne (local.get $arg1) (i32.const 0)) (i32.ne (local.get $arg1) (call $current_process_id)))
      (then (global.set $last_error (i32.const 87)) (call $toolhelp_return (i32.const -1) (i32.const 2)) (return)))
    ;; Process/thread/module snapshots require their real enumerators. Do not
    ;; advertise an empty successful snapshot for those unsupported flags.
    (if (i32.and (local.get $arg0) (i32.const 30)) (then (call $crash_unimplemented (local.get $name_ptr))))
    (if (i32.and (local.get $arg0) (i32.const 0x7fffffe0))
      (then (global.set $last_error (i32.const 87)) (call $toolhelp_return (i32.const -1) (i32.const 2)) (return)))
    (call $toolhelp_lock)
    (if (i32.and (local.get $arg0) (i32.const 1)) (then
      (local.set $count (i32.const 1))
      (local.set $heap (i32.load offset=4 (global.get $TOOLHELP_HEAPS)))
      (block $counted (loop $count
        (br_if $counted (i32.eqz (local.get $heap)))
        (local.set $count (i32.add (local.get $count) (i32.const 1)))
        (local.set $heap (call $gl32 (i32.add (local.get $heap) (i32.const 4))))
        (br_if $count (i32.lt_u (local.get $count) (i32.const 65536)))))))
    (local.set $snap (call $heap_alloc (i32.add (i32.const 12) (i32.shl (local.get $count) (i32.const 2)))))
    (if (local.get $snap) (then
      (local.set $w (call $g2w (local.get $snap)))
      (i32.store (local.get $w) (i32.load offset=8 (global.get $TOOLHELP_HEAPS)))
      (i32.store offset=4 (local.get $w) (local.get $count))
      (i32.store offset=8 (local.get $w) (local.get $arg0))
      (if (local.get $count) (then
        (i32.store offset=12 (local.get $w) (global.get $PROCESS_HEAP_HANDLE))
        (local.set $i (i32.const 1))
        (local.set $heap (i32.load offset=4 (global.get $TOOLHELP_HEAPS)))
        (block $copied (loop $copy
          (br_if $copied (i32.ge_u (local.get $i) (local.get $count)))
          (i32.store (i32.add (local.get $w) (i32.add (i32.const 12) (i32.shl (local.get $i) (i32.const 2)))) (local.get $heap))
          (local.set $heap (call $gl32 (i32.add (local.get $heap) (i32.const 4))))
          (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $copy)))))
      (i32.store offset=8 (global.get $TOOLHELP_HEAPS) (local.get $snap)))
      (else (global.set $last_error (i32.const 8))))
    (call $toolhelp_unlock)
    (call $toolhelp_return (select (local.get $snap) (i32.const -1) (i32.ne (local.get $snap) (i32.const 0))) (i32.const 2)))
  (func $toolhelp_heap_list (param $snap i32) (param $entry i32) (param $next i32) (result i32)
    (local $count i32) (local $i i32) (local $heap i32) (local $found i32)
    (if (i32.eqz (local.get $entry)) (then (global.set $last_error (i32.const 87)) (return (i32.const 0))))
    (if (i32.ne (call $gl32 (local.get $entry)) (i32.const 16)) (then (global.set $last_error (i32.const 24)) (return (i32.const 0))))
    (call $toolhelp_lock)
    (if (i32.eqz (call $toolhelp_snapshot_link (local.get $snap)))
      (then (call $toolhelp_unlock) (global.set $last_error (i32.const 6)) (return (i32.const 0))))
    (local.set $count (call $gl32 (i32.add (local.get $snap) (i32.const 4))))
    (local.set $found (i32.eqz (local.get $next)))
    (block $end (loop $list
      (br_if $end (i32.ge_u (local.get $i) (local.get $count)))
      (local.set $heap (call $gl32 (i32.add (local.get $snap) (i32.add (i32.const 12) (i32.shl (local.get $i) (i32.const 2))))))
      (if (local.get $found) (then
        (call $gs32 (i32.add (local.get $entry) (i32.const 4)) (call $current_process_id))
        (call $gs32 (i32.add (local.get $entry) (i32.const 8)) (local.get $heap))
        (call $gs32 (i32.add (local.get $entry) (i32.const 12)) (i32.eq (local.get $heap) (global.get $PROCESS_HEAP_HANDLE)))
        (call $toolhelp_unlock) (return (i32.const 1))))
      (local.set $found (i32.eq (local.get $heap) (call $gl32 (i32.add (local.get $entry) (i32.const 8)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $list)))
    (call $toolhelp_unlock) (global.set $last_error (i32.const 18)) (i32.const 0))
  (func $handle_Heap32ListFirst (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (i32.store (global.get $reg_base) (call $toolhelp_heap_list (local.get $arg0) (local.get $arg1) (i32.const 0)))
    (i32.store offset=16 (global.get $reg_base) (i32.add (i32.load offset=16 (global.get $reg_base)) (i32.const 12))))
  (func $handle_Heap32ListNext (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (i32.store (global.get $reg_base) (call $toolhelp_heap_list (local.get $arg0) (local.get $arg1) (i32.const 1)))
    (i32.store offset=16 (global.get $reg_base) (i32.add (i32.load offset=16 (global.get $reg_base)) (i32.const 12))))
  (func $toolhelp_heap_entry (param $entry i32) (param $pid i32) (param $heap i32) (param $next i32) (result i32)
    (local $bucket i32) (local $n i32) (local $ptr i32) (local $seen i32) (local $steps i32)
    (if (i32.eqz (local.get $entry)) (then (global.set $last_error (i32.const 87)) (return (i32.const 0))))
    (if (i32.ne (call $gl32 (local.get $entry)) (i32.const 36)) (then (global.set $last_error (i32.const 24)) (return (i32.const 0))))
    (if (i32.ne (local.get $pid) (call $current_process_id)) (then (global.set $last_error (i32.const 87)) (return (i32.const 0))))
    (if (i32.eqz (call $heap_api_handle_valid (local.get $heap))) (then (global.set $last_error (i32.const 6)) (return (i32.const 0))))
    (local.set $seen (i32.eqz (local.get $next)))
    (call $toolhelp_lock)
    (if (i32.eqz (i32.load offset=12 (global.get $TOOLHELP_HEAPS)))
      (then (call $toolhelp_unlock) (global.set $last_error (i32.const 18)) (return (i32.const 0))))
    (loop $buckets
      (local.set $n (i32.load (i32.add (call $g2w (i32.load offset=12 (global.get $TOOLHELP_HEAPS))) (i32.shl (local.get $bucket) (i32.const 2)))))
      (local.set $steps (i32.const 0))
      (block $empty (loop $scan
        (br_if $empty (i32.eqz (local.get $n)))
        (if (i32.eq (call $gl32 (i32.add (local.get $n) (i32.const 4))) (local.get $heap)) (then
          (local.set $ptr (call $gl32 (i32.add (local.get $n) (i32.const 8))))
          (if (local.get $seen) (then
            (call $gs32 (i32.add (local.get $entry) (i32.const 4)) (local.get $ptr))
            (call $gs32 (i32.add (local.get $entry) (i32.const 8)) (local.get $ptr))
            (call $gs32 (i32.add (local.get $entry) (i32.const 12)) (call $gl32 (i32.add (local.get $n) (i32.const 12))))
            (call $gs32 (i32.add (local.get $entry) (i32.const 16)) (i32.const 1))
            (call $gs32 (i32.add (local.get $entry) (i32.const 20)) (i32.const 0))
            (call $gs32 (i32.add (local.get $entry) (i32.const 24)) (i32.const 0))
            (call $gs32 (i32.add (local.get $entry) (i32.const 28)) (local.get $pid))
            (call $gs32 (i32.add (local.get $entry) (i32.const 32)) (local.get $heap))
            (call $toolhelp_unlock) (return (i32.const 1))))
          (local.set $seen (i32.eq (local.get $ptr) (call $gl32 (i32.add (local.get $entry) (i32.const 8)))))))
        (local.set $n (call $gl32 (local.get $n)))
        (local.set $steps (i32.add (local.get $steps) (i32.const 1)))
        (br_if $scan (i32.lt_u (local.get $steps) (i32.const 65536)))))
      (local.set $bucket (i32.add (local.get $bucket) (i32.const 1)))
      (br_if $buckets (i32.lt_u (local.get $bucket) (i32.const 1024))))
    (call $toolhelp_unlock) (global.set $last_error (i32.const 18)) (i32.const 0))
  (func $handle_Heap32First (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (i32.store (global.get $reg_base) (call $toolhelp_heap_entry (local.get $arg0) (local.get $arg1) (local.get $arg2) (i32.const 0)))
    (i32.store offset=16 (global.get $reg_base) (i32.add (i32.load offset=16 (global.get $reg_base)) (i32.const 16))))
  (func $handle_Heap32Next (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (if (i32.eqz (local.get $arg0)) (then
      (global.set $last_error (i32.const 87))
      (call $toolhelp_return (i32.const 0) (i32.const 1)) (return)))
    (i32.store (global.get $reg_base) (call $toolhelp_heap_entry (local.get $arg0)
      (call $gl32 (i32.add (local.get $arg0) (i32.const 28)))
      (call $gl32 (i32.add (local.get $arg0) (i32.const 32))) (i32.const 1)))
    (i32.store offset=16 (global.get $reg_base) (i32.add (i32.load offset=16 (global.get $reg_base)) (i32.const 8))))
